server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://cinema-proyect-db.c7mqi2ug8j4d.us-east-2.rds.amazonaws.com/proyect_cinema
    username: postgres
    password: Jhon0218*
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true


        url: http://localhost:8080/api-docs:yaml