server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ProyectCinema
    username: postgres
    password: 1234
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true


        url: http://localhost:8080/api-docs:yaml